server:
  port: 8080

spring:
  application:
    name: weather-harvester
  profiles:
    active: prod
  security:
    user:
      name: ${MAIN_USER}
      password: ${MAIN_PASSWORD}

management:
  endpoint:
    env:
      post:
        enabled: true

  endpoints:
    web:
      exposure:
        include: refresh, env, health

harvester:
  cleanup:
    months: 12

---

spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER_TEST}
    password: ${POSTGRES_PASSWORD_TEST}

#logging:
#  level:
#    root: debug

---

spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
