server:
  port: 8080

spring:
  application:
    name: weather-harvester
  profiles:
    active: dev

credentials:
  user: ${MAIN_USER}
  user_password: ${MAIN_PASSWORD}
  admin: ${ADMIN}
  admin_password: ${ADMIN_PASSWORD}

management:
  endpoint:
    env:
      post:
        enabled: true

  endpoints:
    web:
      exposure:
        include: refresh, env, health

harvester:
  cleanup:
    months: 12

---

spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

cors:
  allowed-origin: "http://localhost:4200"

#logging:
#  level:
#    root: debug

---

spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

cors:
  allowed-origin: "https://weather-pi.eu"
